### ISSUE TITLE
Code around restinio_control_thread still seems not to be exception-safe

### ISSUE THREAD

**Issue by eao197** [axomem/nucleus#13]
The refactored version of RestServer still has an issue with exception-safety.

You create an actual thread for running RESTinio on a thread pool in the constructor of RestServer. And do joining with that thread in `RestServer::shutdown`. But an exception can be thrown somewhere between the creation of RestServer instance and the call to `RestServer::shutdown`. In that case, `shutdown` won't be called.

I think that the simplest way to dealing with such issues for you is to use something similar to `defer` facility from Go language. In SObjectizer we created a helper [at_scope_exit](https://github.com/Stiffstream/sobjectizer/blob/master/dev/so_5/details/at_scope_exit.hpp) that allows to write like that:
```cpp
RestServer rest_server {RestServerRouter::getRestServerRouter().getRouter()};
auto rest_server_stopper = at_scope_exit([&rest_server]{ rest_server.shutdown(); });
...
```
There is [a similar facility in GSL](https://github.com/microsoft/GSL/blob/master/include/gsl/gsl_util#L55-L93) under the name `finally`. Or you can find another implementation [here](https://oded.blog/2017/10/05/go-defer-in-cpp/).

**Comment by seghcder** [comment]
It seems calling initiate_shutdown a second time in the destructor was causing an occasional std:system_error exception with a message re bad file descriptor. I tried catching but it seemed to escape that.

I've removed the shutdown function and moved it all to the destructor. It should be more exception safe (?), but with a potential future logic error that a ReST call is executed after the AppManager state is set to shutdown. However, at present this doesn't cause any issues.

**Comment by seghcder** [comment]
Coming back to this issue... I'm wondering if your on_pool_runner_t might be a better approach... ie define it as a member variable and init it in the RestServer constructor, and the server will be cleaned up automatically without any destructor needed?

Regarding your comment [above](https://github.com/axomem/nucleus/issues/13#issue-476519374)   ... would rest_server_stopper then be a member variable? Would we still need the control thread here?

Lastly, is there a way to wait until all existing requests are closed and then terminate, rather than terminate in flight requests? It might mean I need a way to reject requests on the app side if the app state is shutting down?

**Comment by eao197** [comment]
I don't remember details of that issue, but RESTinio received some new features since Aug 2019: [run_async function](https://stiffstream.com/en/docs/restinio/0.6/usingrestiniorun.html#run-async-function) and [on_pool_runner_t class](https://stiffstream.com/en/docs/restinio/0.6/usingrestiniorun.html#a-helper-class-on-pool-runner-t). It seems that they can simplify the usage of RESTinio in your case.

> Lastly, is there a way to wait until all existing requests are closed and then terminate, rather than terminate in flight requests?

In the current version of RESTinio you can only have some global* flag and check that flag manually in request handlers.

* this flag need not necessarily be global

**Comment by seghcder** [comment]
I'm implementing on_pool_runner_t at the moment. 

In your docs [here](https://stiffstream.com/en/docs/restinio/0.6/usingrestiniorun.html#a-helper-class-on-pool-runner-t), you might want to show that you need to call `runner.start()`, or have I missed something? :-)

Would you happen to have some example code re how to use `start()` with the callbacks?

**Comment by seghcder** [comment]
Here's the first attempt at the callbacks - https://github.com/seghcder/nucleus/blob/b53ec9bdffbe27ea978b10921b8f5f97ec1ce814/src/RestServer.cpp#L72-L82

**Comment by eao197** [comment]
> In your docs here, you might want to show that you need to call runner.start(), or have I missed something? :-)

You're right, the example in the docs should be expanded. Thank you.

> Would you happen to have some example code re how to use start() with the callbacks?

I'll think about it.
For now, you can take a look at the implementation of `running_server_instance_t::start`, where `on_pool_runner_t::start` with callbacks is called: https://github.com/Stiffstream/restinio/blob/c34f83a68e60537eba52e2d076ed22495ad4c5df/dev/restinio/http_server_run.hpp#L973-L984

**Comment by eao197** [comment]
Just found that almost the same example of `start` with callbacks is [shown in Doxygen-generated API Reference Manual](https://stiffstream.com/en/docs/restinio/0.6-api/classrestinio_1_1on__pool__runner__t.html#a9d8da014a87db7492a41a8a6c77c125e).

**Comment by seghcder** [comment]
I did find that page but didn't page down far enough it seems. I now see it in the doxygen comments in the source too. Thanks.
