### ISSUE TITLE
Establish test framework

### ISSUE THREAD

**Issue by seghcder** [axomem/nucleus#21]
Set up tests for nucleus core and example apps. 

Options might be - 
- Cmake CTest
- Follow the LibPMemObj-cpp approach. There is a lot of custom Cmake script there
- GoogleTest https://github.com/google/googletest 

Also, we need a way to call APIs to test those. Perhaps having a requests library would also be a useful module. eg https://github.com/whoshuu/cpr

Another option is to drive testing from Python, but that adds another dependency

**Comment by ngrodzitski** [comment]
Is your list of options is kind-of "choose one"?

It looks more like a description of a discipline of testing to me. Something like 3 basic quiestions to be answered:
  * _How to describe unit tests in your project and running them?_ Use CMake standard approach with CTest: `enable_testing()`, `add_test()` and all that stuff. If the project is already a CMake-based one then it would be very surprising not to use CTest, which is helper utility having lots of ways to provide your test results to various CI systems. So, yes, use CTest.
  * _How cmake-scripts and where to put tests int you project tree?_ Yep, there are lots of nice scripts showing how to organize tests in your project. Why inventing yours from scratch... Use something you find appropriate and adopt for you case.
  * _Actual test framework?_ `gtest` is good. Also I have a good experience with [catch2](https://github.com/catchorg/Catch2). And lots of others. I would say if there are no certain requirements just go with gtest (if you are ok to compile 3rd-party lib) or use Catch2 (header only).

**Comment by eao197** [comment]
> or use Catch2 (header only)

[doctest](https://github.com/onqtam/doctest) is a good alternative to Catch2 with much faster compilation times (even if main-function for Catch2 is placed in a separate library).

**Comment by seghcder** [comment]
Added initial test framework in https://github.com/axomem/nucleus/commit/95703f1465f906a039eb330260f9139ae03bc0ea

Yes, ended up using CTest. It's basic to start. I haven't decided on a C++ test framework as yet. At the moment using native CTest and shell for basic tests and fixtures, and Python for testing the APIs.  Also set up to run as a github action on commit - https://github.com/axomem/nucleus/actions

More to come - 
* Probably leaning more towards catch2 for integrated C++ testing (simpler, header only)
* Expanding test coverage (and measuring)
* SonarQube or similar integration
* Investigate https://github.com/whoshuu/cpr as an alternative to Python
